include $(GNUSTEP_MAKEFILES)/common.make

TEST_TOOL_NAME = t_AlertPanelScrolling t_EauMenuWindowFilter

ADDITIONAL_CPPFLAGS += -I$(GNUSTEP_MAKEFILES)/TestFramework

t_AlertPanelScrolling_OBJC_FILES = t_AlertPanelScrolling.m
t_EauMenuWindowFilter_OBJC_FILES = t_EauMenuWindowFilter.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make
