include $(GNUSTEP_MAKEFILES)/common.make

TEST_TOOL_NAME = t_GBMenuWindowFilter

ADDITIONAL_CPPFLAGS += -I$(GNUSTEP_MAKEFILES)/TestFramework

t_GBMenuWindowFilter_OBJC_FILES = t_GBMenuWindowFilter.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make
