include $(GNUSTEP_MAKEFILES)/common.make

TEST_TOOL_NAME = t_GBMenuSafeTriangle

ADDITIONAL_CPPFLAGS += -I$(GNUSTEP_MAKEFILES)/TestFramework

t_GBMenuSafeTriangle_OBJC_FILES = t_GBMenuSafeTriangle.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make
